#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pyldap
Version  : 2.4.25.1
Release  : 1
URL      : http://pypi.debian.net/pyldap/pyldap-2.4.25.1.tar.gz
Source0  : http://pypi.debian.net/pyldap/pyldap-2.4.25.1.tar.gz
Summary  : Python modules for implementing LDAP clients
Group    : Development/Tools
License  : Python-2.0
Requires: pyldap-python
BuildRequires : openldap-dev
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : setuptools
Patch1: disable-sasl.patch

%description
======
pyldap
======
.. image:: https://travis-ci.org/pyldap/pyldap.svg?branch=master
:target: https://travis-ci.org/pyldap/pyldap
:alt: Continuous integration status

%package python
Summary: python components for the pyldap package.
Group: Default

%description python
python components for the pyldap package.


%prep
%setup -q -n pyldap-2.4.25.1
%patch1 -p1

%build
export LANG=C
python2 setup.py build -b py2

%install
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
